<x-user-table :index="$index" :employee="[
    'id' => $user->id,
    'prefix' => $user->prefix,
    'name' => $user->name,
    'code' => $user->employee_id,
    'position' => $user->position?->name ?? '',
    'job_level' => $user->jobLevel?->name ?? '',
    'type' => $user->personnel_type,
    'contact' => $user->phone,
    'email' => $user->email,
    'bio' => $user->bio,
    'education_history' => $user->education_history_entries,
    'status' => $user->status,
    'position_id' => $user->position_id,
    'job_level_id' => $user->job_level_id,
    'department_id' => $user->department_id,
    'role' => $user->roles->first()?->name ?? '',
    'role_names' => $user->roles->pluck('name')->all(),
]" />
